### ISSUE TITLE
0.2.0 pypi release doesn't install

### ISSUE THREAD

**Issue by rkhwaja** [PyFilesystem/fs.dropboxfs#1]
I get the following installing on python 3.7 (windows and macos)

Collecting fs.dropboxfs
  Downloading https://files.pythonhosted.org/packages/45/77/4ccf2f3d220791bc41beb19ad07b02723a279d376cdf437822a19e5382b
/fs.dropboxfs-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\rkhwaja\AppData\Local\Temp\pip-install-tctd2y6r\fs.dropboxfs\setup.py", line 21, in <module>
        with io.open('HISTORY.rst', 'r', encoding='utf8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.rst'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\rkhwaja\AppData\Local\Temp\pip-install-tctd2y6r
fs.dropboxfs\

**Comment by rkhwaja** [comment]
I downloaded the source and rebuilt the wheel and it installs from that wheel. So all you need to do is bump the version and upload a new build.
I'd do it myself but it's awkward for me to make a bump-version PR for your repo because I still have my old repo which is an ancestor of this one.

**Comment by dargueta** [comment]
This'll prevent it (and other things like it) from happening again: https://github.com/PyFilesystem/fs.dropboxfs/pull/3
